# FILE: docker-compose.yml
# version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/
    volumes:
      - ./backend:/usr/src/app
    command: "npm start"

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
    command: "npm run serve"

volumes:
  mongodb_data:
